// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ExponentialRateModel$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ExponentialRateModel";
  readonly sourceName: "contracts/pool/ExponentialRateModel.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"prod1","type":"uint256"}],"name":"PRBMath__MulDivFixedPointOverflow","type":"error"},{"inputs":[],"name":"baseRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getDailyRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getPerSecondRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"k","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080806040523461002c57662386f26fc100005f5567414f121108fd000060015561028290816100318239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081631f68f20a146100ed57508063577640941461005357806379138383146100b8578063b4f40c611461009b5763b811394614610053575f80fd5b3461009757602036600319011261009757602061008f61008861008361007b600435806101ba565b6001546101ba565b610127565b5f546101ba565b604051908152f35b5f80fd5b34610097575f366003190112610097576020600154604051908152f35b34610097576020366003190112610097576020620151806100e461008861008361007b600435806101ba565b04604051908152f35b34610097575f366003190112610097576020905f548152f35b9190820180921161011357565b634e487b7160e01b5f52601160045260245ffd5b670de0b6b3a7640000818101809111610113578180809261014882806101ba565b60011c908161015691610106565b91610160916101ba565b60039004908161016f91610106565b91610179916101ba565b60021c908161018791610106565b91610191916101ba565b6005900490816101a091610106565b916101aa916101ba565b600690046101b791610106565b90565b5f19828209828202908180821091039381850390670de0b6b3a764000094858310156102335790859109916706f05b59d3b1ffff8311951461022c577faccb18165bd6fe31ae1cf318dc5b51eee0e1ba569b88cd74c1773b91fac106699350828211900360ee1b910360121c17020190565b5050040190565b60405163698d9a0160e11b815260048101849052602490fdfea2646970667358221220830506a776e2a8d60f277c77658fa62a1c0725ded2bc324d3aafbeffb1616cfe64736f6c63430008180033";
  readonly deployedBytecode: "0x6080806040526004361015610012575f80fd5b5f3560e01c9081631f68f20a146100ed57508063577640941461005357806379138383146100b8578063b4f40c611461009b5763b811394614610053575f80fd5b3461009757602036600319011261009757602061008f61008861008361007b600435806101ba565b6001546101ba565b610127565b5f546101ba565b604051908152f35b5f80fd5b34610097575f366003190112610097576020600154604051908152f35b34610097576020366003190112610097576020620151806100e461008861008361007b600435806101ba565b04604051908152f35b34610097575f366003190112610097576020905f548152f35b9190820180921161011357565b634e487b7160e01b5f52601160045260245ffd5b670de0b6b3a7640000818101809111610113578180809261014882806101ba565b60011c908161015691610106565b91610160916101ba565b60039004908161016f91610106565b91610179916101ba565b60021c908161018791610106565b91610191916101ba565b6005900490816101a091610106565b916101aa916101ba565b600690046101b791610106565b90565b5f19828209828202908180821091039381850390670de0b6b3a764000094858310156102335790859109916706f05b59d3b1ffff8311951461022c577faccb18165bd6fe31ae1cf318dc5b51eee0e1ba569b88cd74c1773b91fac106699350828211900360ee1b910360121c17020190565b5050040190565b60405163698d9a0160e11b815260048101849052602490fdfea2646970667358221220830506a776e2a8d60f277c77658fa62a1c0725ded2bc324d3aafbeffb1616cfe64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/pool/ExponentialRateModel.sol";
  readonly buildInfoId: "solc-0_8_24-90400f2b29e1ab6d772eccdb956b8a125eaef08a";
};

export interface IExponentialRateModel$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IExponentialRateModel";
  readonly sourceName: "contracts/pool/ExponentialRateModel.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getDailyRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getPerSecondRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/pool/ExponentialRateModel.sol";
  readonly buildInfoId: "solc-0_8_24-90400f2b29e1ab6d772eccdb956b8a125eaef08a";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ExponentialRateModel"]: ExponentialRateModel$Type
    ["IExponentialRateModel"]: IExponentialRateModel$Type;
    ["contracts/pool/ExponentialRateModel.sol:ExponentialRateModel"]: ExponentialRateModel$Type
    ["contracts/pool/ExponentialRateModel.sol:IExponentialRateModel"]: IExponentialRateModel$Type;
  }
}