// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBondingCurve$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBondingCurve";
  readonly sourceName: "contracts/interfaces/IPoolContracts.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"buy","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"bnbAmount","type":"uint256"}],"name":"getBuyPrice","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"tokenAmount","type":"uint256"}],"name":"getSellPrice","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"isListed","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"tokenAmount","type":"uint256"}],"name":"sell","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPoolContracts.sol";
  readonly buildInfoId: "solc-0_8_24-90400f2b29e1ab6d772eccdb956b8a125eaef08a";
};

export interface IBuyAndBurnEngine$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBuyAndBurnEngine";
  readonly sourceName: "contracts/interfaces/IPoolContracts.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"deposit","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"minTokensOut","type":"uint256"}],"name":"executeBurn","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"totalBurned","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPoolContracts.sol";
  readonly buildInfoId: "solc-0_8_24-90400f2b29e1ab6d772eccdb956b8a125eaef08a";
};

export interface ICreatorRewardManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ICreatorRewardManager";
  readonly sourceName: "contracts/interfaces/IPoolContracts.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"asset","type":"address"}],"name":"claim","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address[]","name":"assets","type":"address[]"}],"name":"claimMultiple","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"address","name":"beneficiary","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint256","name":"cliffDuration","type":"uint256"},{"internalType":"uint256","name":"vestingDuration","type":"uint256"}],"name":"createVesting","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"address","name":"beneficiary","type":"address"}],"name":"pendingClaim","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"address","name":"beneficiary","type":"address"}],"name":"vestingInfo","outputs":[{"internalType":"uint256","name":"totalAmount","type":"uint256"},{"internalType":"uint256","name":"claimedAmount","type":"uint256"},{"internalType":"uint256","name":"startTimestamp","type":"uint256"},{"internalType":"uint256","name":"cliffEnd","type":"uint256"},{"internalType":"uint256","name":"vestingEnd","type":"uint256"},{"internalType":"bool","name":"exists","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPoolContracts.sol";
  readonly buildInfoId: "solc-0_8_24-90400f2b29e1ab6d772eccdb956b8a125eaef08a";
};

export interface IExponentialRateModel$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IExponentialRateModel";
  readonly sourceName: "contracts/interfaces/IPoolContracts.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getDailyRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"},{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getPerSecondRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"},{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPoolContracts.sol";
  readonly buildInfoId: "solc-0_8_24-90400f2b29e1ab6d772eccdb956b8a125eaef08a";
};

export interface ILinearRateModel$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ILinearRateModel";
  readonly sourceName: "contracts/interfaces/IPoolContracts.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getPerSecondRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"},{"inputs":[{"internalType":"uint256","name":"utilization","type":"uint256"}],"name":"getRate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPoolContracts.sol";
  readonly buildInfoId: "solc-0_8_24-90400f2b29e1ab6d772eccdb956b8a125eaef08a";
};

export interface IPriceOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IPriceOracle";
  readonly sourceName: "contracts/interfaces/IPoolContracts.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"getPrice","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"updateEffectivePrice","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"uint256","name":"newPrice","type":"uint256"}],"name":"updateTwapPrice","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPoolContracts.sol";
  readonly buildInfoId: "solc-0_8_24-90400f2b29e1ab6d772eccdb956b8a125eaef08a";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBondingCurve"]: IBondingCurve$Type
    ["IBuyAndBurnEngine"]: IBuyAndBurnEngine$Type
    ["ICreatorRewardManager"]: ICreatorRewardManager$Type
    ["IExponentialRateModel"]: IExponentialRateModel$Type
    ["ILinearRateModel"]: ILinearRateModel$Type
    ["IPriceOracle"]: IPriceOracle$Type;
    ["contracts/interfaces/IPoolContracts.sol:IBondingCurve"]: IBondingCurve$Type
    ["contracts/interfaces/IPoolContracts.sol:IBuyAndBurnEngine"]: IBuyAndBurnEngine$Type
    ["contracts/interfaces/IPoolContracts.sol:ICreatorRewardManager"]: ICreatorRewardManager$Type
    ["contracts/interfaces/IPoolContracts.sol:IExponentialRateModel"]: IExponentialRateModel$Type
    ["contracts/interfaces/IPoolContracts.sol:ILinearRateModel"]: ILinearRateModel$Type
    ["contracts/interfaces/IPoolContracts.sol:IPriceOracle"]: IPriceOracle$Type;
  }
}