// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUniswapV2Router02"]: never
    ["IWUSDC"]: never
    ["ICreatorRewardManager"]: never
    ["ISimpleFactory"]: never
    ["ISimplePair"]: never
    ["IBondingCurve"]: never
    ["IExponentialRateModel"]: never;
  }
}